name: CI/CD for Strapi App

on:
  push:
    branches:
      - master  # Trigger workflow on push to main branch
  pull_request:
    branches:
      - master  # Trigger workflow on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the repository code

      - name: Install Node.js
        uses: actions/setup-node@v4  # Set up Node.js environment
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install  # Install npm dependencies

      - name: Run tests and linter
        run: |
          npm run lint  # Example command for linting
          npm run test  # Example command for running tests

  deploy:
    runs-on: ubuntu-latest

    needs: build  # Deploy job depends on successful completion of build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Install Node.js
        uses: actions/setup-node@v2  # Set up Node.js environment
        with:
          node-version: '14'

      - name: Install PM2
        run: npm install pm2 -g  # Install PM2 globally

      - name: Stop existing PM2 processes
        run: pm2 delete all || true  # Stop all running PM2 processes if any

      - name: Start Strapi app with PM2
        run: pm2 start npm --name "strapi-app" -- start  # Start Strapi app with PM2

